# ETF Stats Configuration
# Configuration file for ETF data extraction

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  directory: "logs"
  console_output: true
  file_output: true
  structured_logging: true

# Output Configuration
output:
  directory: "data"
  excel_format: true
  timestamp_files: true
  backup_previous: true

# Web Scraping Configuration
scraping:
  request_timeout: 30
  max_retries: 3
  retry_delay_base: 2
  retry_delay_max: 10
  browser_headless: true
  browser_timeout: 60
  page_load_wait: 3
  user_agent_rotation: true
  respect_robots_txt: false
  concurrent_requests: 5

# Data Validation Configuration
validation:
  require_ticker: true
  require_cusip: true
  allow_missing_yields: true
  validate_cusip_format: true
  clean_ticker_symbols: true

# Error Handling Configuration
error_handling:
  continue_on_single_failure: true
  fail_threshold_percentage: 50
  log_all_errors: true
  create_error_report: true

# Development Configuration
development:
  test_mode: false
  test_fund_limit: 5
  debug_requests: false
  save_html_responses: false

# Automation Configuration
automation:
  timestamp_format: "%Y%m%d_%H%M%S"
  daily_filename_format: "schwab_etf_funds_{date}.xlsx"
  backup_filename_format: "{original}_backup_{timestamp}.xlsx"
  
  # Comparison settings
  compare_with_previous: true
  previous_file_pattern: "schwab_etf_funds_*.xlsx"

# Performance Monitoring
performance:
  track_response_times: true
  log_memory_usage: true
  profile_execution: false

# Fund Categories Configuration
fund_categories:
  etf:
    - name: "Equity ETFs"
      description: "Exchange-traded funds focused on equity markets"
    - name: "Fixed Income ETFs" 
      description: "Bond and fixed-income ETFs"
    - name: "Municipal ETFs"
      description: "Municipal bond ETFs"

# Rate Limiting (to be respectful to target sites)
rate_limiting:
  requests_per_minute: 30
  delay_between_requests: 2.0
  burst_allowance: 5

# Cache Configuration (for development/testing)
cache:
  enabled: false
  directory: ".cache"
  ttl_hours: 24
  
# Proxy Configuration (if needed)
proxy:
  enabled: false
  http_proxy: ""
  https_proxy: ""
  auth_required: false
  username: ""
  password: "" 